title: iwashiz home dir
logo: /assets/img/thumnail.png
description: "Welcome !!! Thank you for your comming.  iwashiz のホームディレクトリへようこそ！"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
lang: js
github:
  repository_url: https://github.com/iwashiz0/iamiwashiz0
  repository_name: iamiwashiz0
  owner_url: https://github.com/iwashiz0
  owner_name: iwashiz
  logo: https://github.com/iwashiz0/iamiwashiz/blob/master/assets/img/github-mark-white.png?raw=true
twitter:
  account_url: https://twitter.com/iwashiz0
  logo: https://github.com/iwashiz0/iamiwashiz/blob/master/assets/img/x-logo-white.png?raw=true
qiita:
  account_url: https://qiita.com/iwashiz0
  logo: https://github.com/iwashiz0/iamiwashiz/blob/master/assets/img/qiita-white-icon.png?raw=true